import { icon } from '../core/icons.js';
import { directory, history, saveUser, setActive, resetAccess, saveSettings, requireAdmin, settings } from '../services/admin.service.js';
import { ROLE_LABELS } from '../core/constants.js';
import { getCurrentUser } from '../core/auth.js';
import { escapeHtml as e } from '../core/utils.js';
import { openModal, toast } from '../core/ui.js';
import { resetDemo } from '../seed.js';
const tabs=[['users','Utilisateurs'],['roles','Rôles & accès'],['settings','Paramètres'],['audit','Journal']];
const missions={PARTNER_ADMIN:'Crée et soumet les DUT de son partenaire, gère ses référentiels et demande des plages.',PARTNER_EDITOR:'Prépare et soumet les DUT de son partenaire et consulte ses ressources.',ANTENNA_AGENT:'Examine les dossiers de son antenne, valide ou rejette les DUT.',OIC_ADMIN:'Supervise les DUT au niveau national, traite les demandes de plages et administre la plateforme.',CONTROLLER:'Vérifie les DUT et enregistre les contrôles routiers.',TRANSPORTEUR:'Consulte ses DUT et renseigne le suivi de ses transports.'};
const error=err=>toast({type:'error',title:err.message});
const options=(items,value)=>items.map(([id,label])=>`<option value="${e(id)}" ${id===value?'selected':''}>${e(label)}</option>`).join('');
function codeModal(code){openModal({title:'Nouvel accès créé',text:'Copiez ce mot de passe et transmettez-le au titulaire. Il ne sera plus affiché après fermeture. Les anciens accès réinitialisés ne fonctionnent plus.',bodyHtml:`<label class="field">Mot de passe<input class="input" readonly value="${e(code)}" onclick="this.select()"></label>`,hideCancel:true,confirmLabel:'Fermer'});}
export function render(root,{section='users'}={}){
 const data=directory(),me=getCurrentUser();
 root.innerHTML=`<div class="page-header"><div><h1>Administration</h1><p>Utilisateurs, accès et configuration de votre espace OIC.</p></div></div><nav class="admin-tabs" aria-label="Administration">${tabs.map(([id,label])=>`<a class="btn ${id===section?'btn-primary':'btn-secondary'}" href="#/admin/${id}">${label}</a>`).join('')}</nav><div class="admin-note">POC local · Les comptes et paramètres sont conservés dans ce navigateur. Ils ne sont pas synchronisés avec un serveur.</div><div id="admin-body"></div>`;
 const body=root.querySelector('#admin-body');
 if(section==='users'){
 body.innerHTML=`<div class="admin-stats"><div class="card"><strong>${data.users.length}</strong><span>Utilisateurs</span></div><div class="card"><strong>${data.users.filter(u=>u.active!==false).length}</strong><span>Comptes actifs</span></div><div class="card"><strong>${Object.keys(ROLE_LABELS).length}</strong><span>Rôles disponibles</span></div></div><section class="card admin-panel"><div class="admin-toolbar"><input class="input" id="user-search" placeholder="Rechercher un nom ou un e-mail" aria-label="Rechercher un utilisateur"><select class="select" id="role-filter" aria-label="Filtrer par rôle"><option value="">Tous les rôles</option>${options(Object.entries(ROLE_LABELS),'')}</select><button class="btn btn-primary" id="add-user">Ajouter un utilisateur</button></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Utilisateur</th><th>Rôle</th><th>Rattachement</th><th>Statut</th><th>Actions</th></tr></thead><tbody id="user-rows"></tbody></table></div></section>`;
 const draw=()=>{const q=body.querySelector('#user-search').value.toLowerCase(),role=body.querySelector('#role-filter').value;body.querySelector('#user-rows').innerHTML=data.users.filter(u=>(!role||u.role===role)&&`${u.name} ${u.email}`.toLowerCase().includes(q)).map(u=>`<tr><td><strong>${e(u.name)}</strong>${u.id===me.id?' · vous':''}<br><small>${e(u.email)}</small></td><td>${e(ROLE_LABELS[u.role])}</td><td>${e(u.partnerName||u.antennaName||u.transporterName||'National')}</td><td><span class="badge ${u.active===false?'badge-error':'badge-success'}">${u.active===false?'Inactif':'Actif'}</span></td><td><div class="admin-actions"><button class="btn btn-secondary btn-sm" data-edit="${e(u.id)}">Modifier</button>${u.id!==me.id?`<button class="btn btn-ghost btn-sm" data-reset="${e(u.id)}">Réinitialiser l’accès</button><button class="btn btn-ghost btn-sm" data-toggle="${e(u.id)}">${u.active===false?'Activer':'Désactiver'}</button>`:''}</div></td></tr>`).join('')||'<tr><td colspan="5">Aucun utilisateur trouvé.</td></tr>';};
 draw();body.querySelector('#user-search').oninput=draw;body.querySelector('#role-filter').onchange=draw;
 const edit=u=>{const modal=openModal({title:u?'Modifier l’utilisateur':'Ajouter un utilisateur',confirmLabel:'Enregistrer',bodyHtml:`<form id="user-form" class="admin-form"><label class="field">Nom complet<input name="name" class="input" required maxlength="100" value="${e(u?.name||'')}"></label><label class="field">Adresse e-mail<input name="email" class="input" type="email" required maxlength="160" value="${e(u?.email||'')}"></label><label class="field">Rôle<select name="role" class="select">${options(Object.entries(ROLE_LABELS),u?.role||'PARTNER_EDITOR')}</select></label><label class="field" id="scope-field">Rattachement<select name="scope" class="select"></select></label></form>`,onConfirm:async({close,root:overlay})=>{const form=overlay.querySelector('form');if(!form.reportValidity())return;const btn=overlay.querySelector('[data-action="confirm"]');btn.disabled=true;try{const result=await saveUser(u?.id,Object.fromEntries(new FormData(form)));close();render(root,{section});toast({type:'success',title:'Utilisateur enregistré'});if(result.code)codeModal(result.code);}catch(err){error(err);}finally{btn.disabled=false;}}});
 const form=modal.root.querySelector('form');form.onsubmit=ev=>ev.preventDefault();const scope=()=>{const role=form.elements.role.value,items=role.startsWith('PARTNER_')?data.partners:role==='ANTENNA_AGENT'?data.antennas:role==='TRANSPORTEUR'?data.transporters:[];form.querySelector('#scope-field').hidden=!items.length;form.elements.scope.required=['PARTNER_ADMIN','PARTNER_EDITOR','ANTENNA_AGENT','TRANSPORTEUR'].includes(role);form.elements.scope.innerHTML='<option value="">Choisir…</option>'+options(items.map(x=>[x.id,x.name]),u?.partnerId||u?.antennaId||u?.transporterId);};form.elements.role.onchange=scope;scope();};
 body.querySelector('#add-user').onclick=()=>edit(null);
 body.onclick=ev=>{const editBtn=ev.target.closest('[data-edit]');if(editBtn)edit(data.users.find(u=>u.id===editBtn.dataset.edit));const btn=ev.target.closest('[data-toggle],[data-reset]');if(!btn)return;const u=data.users.find(u=>u.id===(btn.dataset.toggle||btn.dataset.reset)),reset=!!btn.dataset.reset;openModal({title:reset?'Réinitialiser cet accès ?':u.active===false?'Réactiver ce compte ?':'Désactiver ce compte ?',text:`${u.name} — ${u.email}. ${reset?'Un nouveau mot de passe remplacera l’ancien.':'Les sessions existantes seront invalidées.'}`,danger:true,onConfirm:async({close,root:overlay})=>{const confirm=overlay.querySelector('[data-action="confirm"]');confirm.disabled=true;try{const code=reset?await resetAccess(u.id):setActive(u.id,u.active===false);close();render(root,{section});if(code)codeModal(code);else toast({type:'success',title:'Statut mis à jour'});}catch(err){error(err);}finally{confirm.disabled=false;}}});};
 }else if(section==='roles'){
 body.innerHTML=`<p>Les six rôles ont des droits prédéfinis. Leur attribution et leur rattachement se modifient dans l’onglet Utilisateurs.</p><div class="admin-role-grid">${Object.entries(ROLE_LABELS).map(([id,label])=>`<article class="card admin-panel"><span class="badge badge-accent">${data.users.filter(u=>u.role===id).length} compte(s)</span><h2>${e(label)}</h2><p>${missions[id]}</p><small>${id==='OIC_ADMIN'?'Administration des comptes et paramètres autorisée.':'Administration des comptes et paramètres non autorisée.'}</small></article>`).join('')}</div>`;
 }else if(section==='settings'){
 const s=settings();body.innerHTML=`<div class="settings-layout"><form id="settings-form" class="admin-form settings-form">
  <section class="card settings-section"><div class="settings-head"><span class="settings-icon" style="background:var(--navy-soft);color:var(--navy-2)">${icon('shield',{size:18})}</span><div><h2>Identité de la plateforme</h2><p>Ce que voient les utilisateurs dans l’en-tête, les documents et les messages.</p></div></div>
    <div class="settings-grid"><label class="field"><span>Nom de la plateforme <span class="req">*</span></span><input class="input" name="platformName" required maxlength="45" value="${e(s.platformName)}"><small class="hint">45 caractères maximum.</small></label><label class="field"><span>E-mail d’assistance</span><input class="input" name="supportEmail" type="email" placeholder="assistance@oic.ci" value="${e(s.supportEmail)}"><small class="hint">Affiché aux utilisateurs en cas de difficulté.</small></label></div></section>
  <section class="card settings-section"><div class="settings-head"><span class="settings-icon" style="background:var(--warning-soft);color:var(--warning)">${icon('clock',{size:18})}</span><div><h2>Alertes et délais</h2><p>Seuils à partir desquels un dossier est signalé dans le centre d’actions.</p></div></div>
    <div class="settings-grid"><label class="field"><span>Dossier en attente signalé après</span><div class="input-unit"><input class="input" name="overdueDays" type="number" min="1" max="90" required value="${s.overdueDays}"><b>jours</b></div><small class="hint">Entre 1 et 90 jours.</small></label></div></section>
  <section class="card settings-section"><div class="settings-head"><span class="settings-icon" style="background:var(--success-soft);color:var(--success)">${icon('layers',{size:18})}</span><div><h2>Plages de numéros</h2><p>Valeurs proposées par défaut lors d’une nouvelle demande ; les demandes existantes ne changent pas.</p></div></div>
    <div class="settings-grid"><label class="field"><span>Quantité proposée</span><div class="input-unit"><input class="input" name="rangeQuantity" type="number" min="1" max="10000" required value="${s.rangeQuantity}"><b>numéros</b></div><small class="hint">Entre 1 et 10 000.</small></label><label class="field"><span>Tarif unitaire proposé</span><div class="input-unit"><input class="input" name="rangePrice" type="number" min="0" max="1000000" step="0.01" required value="${s.rangePrice}"><b>FCFA</b></div><small class="hint">Par numéro de DUT.</small></label></div></section>
  <div class="settings-bar"><span class="text-muted">Les modifications s’appliquent immédiatement, dans ce navigateur.</span><button class="btn btn-primary" type="submit">${icon('check',{size:15})} Enregistrer les paramètres</button></div>
 </form>
 <aside class="settings-aside">
  <section class="card settings-summary"><div class="card-header"><h3>Valeurs en vigueur</h3></div><dl class="sup-identity"><div><dt>Plateforme</dt><dd><strong>${e(s.platformName)}</strong></dd></div><div><dt>Assistance</dt><dd>${e(s.supportEmail||'— non renseignée —')}</dd></div><div><dt>Dossier signalé après</dt><dd>${e(String(s.overdueDays))} jour${s.overdueDays>1?'s':''}</dd></div><div><dt>Plage proposée</dt><dd>${e(String(s.rangeQuantity))} numéros · ${e(String(s.rangePrice))} FCFA l’unité</dd></div><div><dt>Valeur d’une plage</dt><dd><strong>${e(new Intl.NumberFormat('fr-FR').format(Math.round(Number(s.rangeQuantity)*Number(s.rangePrice))))} FCFA</strong></dd></div></dl></section>
  <section class="card settings-help"><div class="card-header"><h3>Où ces réglages s’appliquent</h3></div><ul class="settings-help-list"><li>${icon('shield',{size:14})}<span><b>Nom et assistance</b> : en-tête, page de connexion, pied des documents.</span></li><li>${icon('clock',{size:14})}<span><b>Délai d’alerte</b> : centre d’actions et tableaux de bord (dossiers « en attente »).</span></li><li>${icon('layers',{size:14})}<span><b>Plages</b> : formulaire de demande de plage, pré-rempli pour les partenaires.</span></li></ul></section>
  <section class="card settings-section settings-danger"><div class="settings-head"><span class="settings-icon" style="background:var(--error-soft);color:var(--error)">${icon('alertTriangle',{size:18})}</span><div><h2>Réinitialiser la démonstration</h2><p>Supprime les données locales du POC et rétablit comptes et dossiers de démonstration. Irréversible.</p></div></div><button class="btn btn-danger btn-block" id="reset-platform">Réinitialiser le POC</button></section>
 </aside></div>`;
 body.querySelector('form').onsubmit=ev=>{ev.preventDefault();try{saveSettings(Object.fromEntries(new FormData(ev.target)));window.dispatchEvent(new HashChangeEvent('hashchange'));toast({type:'success',title:'Paramètres enregistrés'});}catch(err){error(err);}};
 body.querySelector('#reset-platform').onclick=()=>openModal({title:'Effacer les données du POC ?',text:'Les utilisateurs ajoutés, DUT, suivis et paramètres locaux seront supprimés. Cette opération est irréversible.',danger:true,confirmLabel:'Effacer et réinitialiser',onConfirm:({close})=>{try{requireAdmin();resetDemo();close();window.location.hash='/login';}catch(err){error(err);}}});
 }else if(section==='audit'){
 body.innerHTML=`<section class="card admin-panel"><h2>Journal d’administration</h2><p>Les 500 dernières opérations locales, sans mots de passe.</p><div class="table-wrap"><table class="data-table"><thead><tr><th>Date</th><th>Action</th><th>Cible</th><th>Administrateur</th></tr></thead><tbody>${history().map(a=>`<tr><td>${e(new Date(a.at).toLocaleString('fr-FR'))}</td><td>${e(a.label)}</td><td>${e(a.target)}</td><td>${e(a.actor)}</td></tr>`).join('')||'<tr><td colspan="4">Aucune opération pour le moment.</td></tr>'}</tbody></table></div></section>`;
 }
}
